"""Generate a fresh EOA signer wallet for PolyGate.

The generated EOA is your API *signer*. After running this, connect the same
wallet on polymarket.com to provision your **deposit wallet**, then set
FUNDER_ADDRESS in `.env` to that deposit-wallet address.

Security model:
- The private key is written ONLY to the gitignored `.env` file (chmod 600).
- The private key is NEVER printed to the terminal.
- Refuses to overwrite an existing PRIVATE_KEY so a funded wallet can't be
  clobbered by accident.

Run:  ./.venv/bin/python scripts/generate_wallet.py
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path

from eth_account import Account

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"


def env_has_private_key(path: Path) -> bool:
    if not path.exists():
        return False
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("PRIVATE_KEY=") and stripped.split("=", 1)[1].strip():
            return True
    return False


def main() -> None:
    if env_has_private_key(ENV_PATH):
        raise SystemExit(
            f"Refusing to overwrite: {ENV_PATH} already contains a PRIVATE_KEY.\n"
            "Delete that line manually if you really want a new wallet."
        )

    acct = Account.create(secrets.token_bytes(32))
    platform_api_key = secrets.token_urlsafe(32)

    env_body = (
        "# === PolyGate configuration ===\n"
        "# Generated by scripts/generate_wallet.py. KEEP THIS FILE SECRET.\n"
        "# Back up PRIVATE_KEY somewhere safe (password manager). If you lose it,\n"
        "# you lose access to the account. If it leaks, funds can be stolen.\n\n"
        "# --- Account ---\n"
        "# PRIVATE_KEY is your EOA signer (generated below). Connect this wallet on\n"
        "# polymarket.com to provision your deposit wallet, then set FUNDER_ADDRESS\n"
        "# to that deposit-wallet address (Profile -> Deposit, shown as 'API use only').\n"
        f"PRIVATE_KEY={acct.key.hex()}\n"
        "FUNDER_ADDRESS=\n\n"
        "# --- Platform REST API ---\n"
        "# Send this as the 'X-API-Key' header on every request to the platform.\n"
        f"PLATFORM_API_KEY={platform_api_key}\n\n"
        "# --- Filled in by `derive-creds` ---\n"
        "# CLOB_API_KEY / CLOB_SECRET / CLOB_PASSPHRASE\n"
    )

    ENV_PATH.write_text(env_body)
    os.chmod(ENV_PATH, 0o600)

    print("New EOA signer wallet created.")
    print(f"  Signer address : {acct.address}")
    print(f"  Saved to       : {ENV_PATH}  (chmod 600, gitignored)")
    print(f"  Platform key   : set (PLATFORM_API_KEY in .env)")
    print()
    print("The private key was NOT printed here on purpose. Read it with:  cat .env")
    print()
    print("Next steps:")
    print("  1. Back up your PRIVATE_KEY from .env.")
    print("  2. Connect this wallet on polymarket.com to create your deposit wallet.")
    print("  3. Set FUNDER_ADDRESS in .env to that deposit-wallet address")
    print("     (Profile -> Deposit, shown as 'API use only').")
    print("  4. Run:  derive-creds")


if __name__ == "__main__":
    main()
